version: '3.1'

services:
  dev:
    container_name: mstaff-micro__router
    image: nginx:alpine
    ports:
      - '20000:80'
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - mstaff-micro.network

networks:
  mstaff-micro.network:
    external: true